[workspace]
resolver = "2"
members = ["crates/pia-rs", "crates/piatui"]
package.edition = "2021"
package.license = "GPL-3.0-or-later"

[workspace.dependencies]
cfg-if = "1.0.0"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
bytemuck = "1.16.1"
