[package]
name = "pia-rs"
version = "0.1.0"
authors = ["Colin Cai <therealcreative0708@gmail.com>"]
edition.workspace = true
license.workspace = true

[lib]

[dependencies]
cfg-if = "1.0.0"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
bytemuck = "1.16.1"
