[package]
name = "pia-rs"
version = "0.1.0"
authors = ["Colin Cai <therealcreative0708@gmail.com>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[lib]

[dependencies]
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
